# Generated by Django 5.1.5 on 2025-03-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comune', models.CharField(max_length=100)),
                ('pro_com_t', models.CharField(max_length=20, unique=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuni', to='archivio_anagrafica.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('comune_nascita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_nati', to='archivio_anagrafica.comune')),
                ('comune_residenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_residenti', to='archivio_anagrafica.comune')),
                ('provincia_nascita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_nati', to='archivio_anagrafica.provincia')),
                ('provincia_residenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_residenti', to='archivio_anagrafica.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='TitoloStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titoli_studio', to='archivio_anagrafica.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.FileField(upload_to='immagini')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='archivio_anagrafica.utente')),
            ],
        ),
    ]
