# Generated by Django 5.1.5 on 2025-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivio_anagrafica', '0002_utente_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
