# Generated by Django 5.1.5 on 2025-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivio_anagrafica', '0003_alter_utente_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
