# Generated by Django 5.1.5 on 2025-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivio_anagrafica', '0004_registroutente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='data_nascita',
            field=models.DateField(null=True),
        ),
    ]
