# Generated by Django 5.1.5 on 2025-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivio_anagrafica', '0005_utente_data_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
